In [15]:
import pandas as pd
import csv
import numpy as np
import os

In [16]:
path = "./AMT_results/"

In [20]:
def csv_to_DF():
    all_video_pairs = pd.DataFrame()
    for csv_file in os.listdir(path):
        if csv_file.startswith("videopair_"):
            new_csv_df = pd.read_csv(path+csv_file)
            all_video_pairs = all_video_pairs.append(new_csv_df)
    return all_video_pairs

In [26]:
def take_100_pseudorand():
    DF100 = all_video_pairs.head(1)
    display(DF100)
    nonmatches = 2
    while len(DF100) < 100:
        for i, sample  in all_video_pairs.iterrows():
            if sample.isna().any():
                continue
            sample_traits = sample[['authentic','organized','comfortable','imaginative','interview']]
            DF100_traits = DF100[['authentic','organized','comfortable','imaginative','interview']]
            if (DF100_traits != sample_traits).sum(axis=1).min() >= nonmatches:
                DF100 = DF100.append(sample)
                display(pd.DataFrame(sample).transpose())
                if len(DF100) == 100:
                    break
        nonmatches = nonmatches - 1
        print nonmatches, len(DF100)
        
    return DF100

In [ ]:
csv_to_DF()
DF100 = take_100_pseudorand()

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
0,3ICOHX7ENDBDB4FWHCS923JAK0OE0S,yUESJPS0wS8.001.mp4,nghDz0el8iI.000.mp4,LEFT,LEFT,RIGHT,RIGHT,DON'T KNOW,LEFT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
1,3P7RGTLO6FDCYH5O5005P48SDJVKA8,cx8IycWgMVs.005.mp4,d_POf1pikX0.003.mp4,LEFT,RIGHT,RIGHT,LEFT,LEFT,LEFT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
2,37PGLWGSJU6R4ZOMHOSI62WBQR0IKA,Bmn4YEhgBDY.000.mp4,RgZTZIf8K8g.002.mp4,LEFT,LEFT,LEFT,LEFT,LEFT,LEFT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
3,3HY86PZXPZIDIT0EDVW9G82KPSUE1V,LmA23EIaXqg.000.mp4,pPtzEnf5afw.001.mp4,RIGHT,RIGHT,RIGHT,RIGHT,RIGHT,RIGHT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
8,3FHTJGYT8O0EJZF74SXNH75U5OFGPI,jmbAPNTJ3Vk.005.mp4,LsPKxJgefks.003.mp4,RIGHT,DON'T KNOW,DON'T KNOW,LEFT,RIGHT,RIGHT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
15,3VIVIU06FLCMUNOP205YLFOFFWVIMF,8qesctueAV0.000.mp4,bYXRyimxh7A.003.mp4,LEFT,LEFT,DON'T KNOW,LEFT,LEFT,DON'T KNOW

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
16,36QZ6V158ADU19WUGEQYGRBW1G0SU9,OMHlfDF99Mw.002.mp4,HWuh0biZQ_c.002.mp4,LEFT,DON'T KNOW,LEFT,LEFT,DON'T KNOW,LEFT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
19,3PEG1BH7AFRHHRAGBE01KFSYV1GKB3,pljK0DEusA0.003.mp4,9yZEb6bdxNY.002.mp4,LEFT,LEFT,RIGHT,LEFT,RIGHT,LEFT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
21,35NNO802AWWSC59PE1KYYUDFKM5INF,eXtskPoi58A.003.mp4,WyLqK6wzYLU.000.mp4,LEFT,DON'T KNOW,RIGHT,LEFT,LEFT,DON'T KNOW

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
25,3K3G488TR3813ER2N9TLDF4FKBMQ50,OwI3Q-qUqDw.002.mp4,uDm7iZuX5DQ.002.mp4,RIGHT,DON'T KNOW,LEFT,DON'T KNOW,RIGHT,RIGHT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
26,3IV1AEQ4DSD3496RQHGFSY2K86WJ85,fuKtMm2WR0g.001.mp4,WuIKjBb7s4Q.001.mp4,RIGHT,LEFT,LEFT,RIGHT,RIGHT,LEFT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
33,3V8JSVE8YZQA8ZBHPK3IUVDUWD2YEC,nGGtTu6dSJE.000.mp4,usG6pVxbQkw.000.mp4,DON'T KNOW,RIGHT,DON'T KNOW,DON'T KNOW,LEFT,DON'T KNOW

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
37,3L2OEKSTWAATZY1QCHHI2LH8LA58YO,Jy716zClCKs.004.mp4,3DURnr95fMg.003.mp4,RIGHT,RIGHT,LEFT,LEFT,RIGHT,RIGHT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
40,3O4VWC1GEX6H3C0LE0LJ1HU9SK43JX,6k8RQViPUTc.000.mp4,FoWuHvikyqU.004.mp4,RIGHT,LEFT,LEFT,RIGHT,LEFT,RIGHT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
41,3KI0JD2ZU2ING0M1WTUK5U1KBG667Z,hd2-msVu9-g.000.mp4,Lj1WuMXFa-4.005.mp4,DON'T KNOW,RIGHT,RIGHT,DON'T KNOW,DON'T KNOW,RIGHT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
51,37NXA7GVSU67ABQ41V320RZKNT1VLN,Zi7QHI_5ipU.005.mp4,Tg8a_iNEamM.005.mp4,DON'T KNOW,DON'T KNOW,DON'T KNOW,DON'T KNOW,DON'T KNOW,DON'T KNOW

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
80,3UDTAB6HH7ZWG8OF91CNAPIZT3890D,2AV8m02PjdU.001.mp4,n8IiQJyqjiE.001.mp4,LEFT,RIGHT,LEFT,DON'T KNOW,RIGHT,LEFT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
114,3FTID4TN8MYOE5L966QM7Q3E5A3YLZ,Gg4OMtVe7lk.002.mp4,yrToGVRf27U.003.mp4,LEFT,LEFT,RIGHT,DON'T KNOW,LEFT,RIGHT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
133,3MVY4USGB7NPSI1UMX1KXONL7LDISR,hsXn0N8bAYs.005.mp4,B8kzwm6ZaUo.003.mp4,RIGHT,DON'T KNOW,DON'T KNOW,RIGHT,DON'T KNOW,RIGHT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
136,3HYV4299H1WVTTKZCG5OVIPS3Y0E8F,LBKbubsgpE8.001.mp4,6TkMavTyimI.002.mp4,LEFT,RIGHT,LEFT,LEFT,LEFT,DON'T KNOW

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
160,322ZSN9Z5HKWZBFUQ846DS9O4MQT4C,OcS4H_dFeOc.004.mp4,bAxlTgobVHE.000.mp4,RIGHT,DON'T KNOW,RIGHT,DON'T KNOW,RIGHT,DON'T KNOW

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
176,31N9JPQXIQISGAY58J2DYIC0K9QNHR,BLc_GvsbI1U.001.mp4,XfUqFt2amrM.000.mp4,DON'T KNOW,LEFT,LEFT,DON'T KNOW,DON'T KNOW,LEFT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
200,3HJ1EVZS2PJY10JYM5US38G021Y3RP,NkFJuN8fBDU.000.mp4,t30ERiF6b50.003.mp4,RIGHT,RIGHT,DON'T KNOW,RIGHT,LEFT,RIGHT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
213,3KTCJ4SCVH1BUHSRUTKSTG7TYULM1S,cP_dSXql7z8.005.mp4,y7MEVu2nyes.004.mp4,DON'T KNOW,LEFT,LEFT,DON'T KNOW,RIGHT,DON'T KNOW

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
219,3VW0145YLZCIPY8VKIQYXG3FSBLJMT,1izSTcQI7H4.004.mp4,ezMO8EHKAVw.002.mp4,RIGHT,LEFT,RIGHT,LEFT,DON'T KNOW,RIGHT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
223,386659BNTMHER3LK5OXUVJ0GVRK10W,MuYYY3XaJ7Q.001.mp4,PooFvZH6fK0.000.mp4,LEFT,RIGHT,DON'T KNOW,DON'T KNOW,RIGHT,RIGHT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
233,37ZQELHEQ1YE8OZGZGIQQNKW1VPNM0,NTATNIs2sSc.002.mp4,cA43Gfcg0QA.005.mp4,LEFT,LEFT,DON'T KNOW,RIGHT,LEFT,LEFT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
244,3GMLHYZ0LFXRXV83FKINYDZXI1WYUT,JzXnxQDnwWE.002.mp4,xZ9iwqHw7GY.001.mp4,RIGHT,RIGHT,DON'T KNOW,RIGHT,RIGHT,DON'T KNOW

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
259,34O39PNDK7834VNB1Y9YLRECQTBRB4,mGWS0Akp08E.001.mp4,cjbh1lfr43c.001.mp4,DON'T KNOW,RIGHT,DON'T KNOW,LEFT,DON'T KNOW,RIGHT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
266,31ANT7FQN92OQLSZ4J6R41CETORH5W,HPEemWelY1E.003.mp4,t30ERiF6b50.003.mp4,RIGHT,RIGHT,LEFT,RIGHT,LEFT,LEFT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
279,3D17ECOUOFVA8VKHOBFDXHYNY3413R,J9MfhPoJOaw.004.mp4,EA8BEYAZqAA.000.mp4,LEFT,LEFT,RIGHT,DON'T KNOW,DON'T KNOW,DON'T KNOW

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
298,36AZSFEYZ50VX24SAIE8MO3FBZOBVH,4XdZDodpzac.001.mp4,II2KVV-uLNI.003.mp4,RIGHT,DON'T KNOW,LEFT,RIGHT,DON'T KNOW,DON'T KNOW

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
343,3Z56AA6EK50613TO0ZW9OCYA6516MA,G-25EWOIGNs.004.mp4,GQczMGrVgbc.001.mp4,DON'T KNOW,RIGHT,LEFT,RIGHT,DON'T KNOW,RIGHT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
346,39HYCOOPKPL5MC83AM4NUI82NROMDI,feg-RNvT-t0.002.mp4,ZRrduU1CXqU.001.mp4,RIGHT,DON'T KNOW,RIGHT,RIGHT,LEFT,RIGHT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
375,3XEDXEGFX4OGX476DY3C0YWF4XKK0I,_X6_C_Oy9VA.002.mp4,yRVvI1x2DBI.004.mp4,LEFT,LEFT,DON'T KNOW,RIGHT,RIGHT,RIGHT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
385,3RKHNXPHGXWWDQJMB5HWP5KMKMNKUK,WD1WsbooU2w.001.mp4,tiVKJWLzmk4.002.mp4,RIGHT,RIGHT,DON'T KNOW,DON'T KNOW,DON'T KNOW,LEFT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
398,32TZXEA1OMKVQR3LOPKW7MQTC3041F,XJj34u5IzU0.003.mp4,HekcZ0Em60E.001.mp4,RIGHT,LEFT,DON'T KNOW,LEFT,DON'T KNOW,LEFT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
511,3V0TR1NRVB2RKFGLK8DPINJWGX64A3,DyZlhseSuec.004.mp4,bJktioZ5Yxk.002.mp4,DON'T KNOW,LEFT,RIGHT,RIGHT,LEFT,DON'T KNOW

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
635,3CKVGCS3PH5ELNKEI7CERKNPLRXS07,4NzqG0XwOWg.003.mp4,MCr6FmFAhak.003.mp4,LEFT,RIGHT,DON'T KNOW,LEFT,RIGHT,LEFT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
657,3HY86PZXPZIDIT0EDVW9G82KPSU1EI,dQOeQYWIgm8.005.mp4,KNx7_ajRwDI.005.mp4,LEFT,DON'T KNOW,DON'T KNOW,LEFT,LEFT,LEFT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
829,3ZRKL6Z1E93BWRVZW91HCCA5S8MSGA,LLP-oZfo8oE.005.mp4,SYlV95nPTPs.000.mp4,LEFT,DON'T KNOW,LEFT,LEFT,RIGHT,DON'T KNOW

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
942,3TLFH2L6YAOMWX07MULIKDCQK8W2TR,Zb5BstGpJ48.001.mp4,ABWFQuPG1LA.000.mp4,RIGHT,RIGHT,LEFT,DON'T KNOW,DON'T KNOW,DON'T KNOW

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
964,3A520CCNWO09CHDE9EP2R9VNTM0AEF,mZ2CHgzwDt0.002.mp4,yUESJPS0wS8.002.mp4,RIGHT,LEFT,DON'T KNOW,DON'T KNOW,RIGHT,LEFT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
985,3QHITW7OYP9Y9K3JI5K2LQK1CPPAQS,CUiG7UZ9A3k.004.mp4,75XbCb7G8kw.002.mp4,LEFT,RIGHT,RIGHT,LEFT,RIGHT,DON'T KNOW

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
1022,3BO3NEOQM1HLSMF05XFTCOTFLF7AIO,3lV-sr3NOUo.005.mp4,WUNXs4r_xCU.002.mp4,RIGHT,DON'T KNOW,DON'T KNOW,DON'T KNOW,LEFT,RIGHT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
1175,3JAOYN9IHM26IYYWBFTWLADKWNJ33M,X5aKCrWf6a4.005.mp4,GWOtluILlk4.004.mp4,DON'T KNOW,RIGHT,RIGHT,RIGHT,DON'T KNOW,DON'T KNOW

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
1446,35YHTYFL1H3LAJG8FK045EU0QXGVFJ,y6sy0HBe-Zs.005.mp4,_fJcW5234bY.002.mp4,LEFT,DON'T KNOW,LEFT,DON'T KNOW,LEFT,LEFT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
1538,3ULIZ0H1VB5DMA7L2U36CEW7CZW15I,fY4tctYZTz8.002.mp4,UKHSKkb0V1o.004.mp4,RIGHT,DON'T KNOW,DON'T KNOW,RIGHT,LEFT,DON'T KNOW

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
2487,3N7PQ0KLI6P9SWET0ZAS41HHNCA3EE,YygvfVxOWP8.004.mp4,IlbODduDCb4.005.mp4,RIGHT,RIGHT,LEFT,DON'T KNOW,LEFT,RIGHT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
2500,31KPKEKW4BDF413C7LQJ1VDPH3DB0R,--Ymqszjv54.005.mp4,X9AEEGzWSU8.001.mp4,DON'T KNOW,LEFT,DON'T KNOW,RIGHT,DON'T KNOW,DON'T KNOW

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
3887,3BS6ERDL9473X9NBN6X65MBGXRBD61,LSqijVxP0EM.001.mp4,uDm7iZuX5DQ.000.mp4,RIGHT,DON'T KNOW,LEFT,LEFT,LEFT,RIGHT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
4673,37VHPF5VYD3GWV0LGPZT5UPPIMR8CK,4yogPbHFQ9o.001.mp4,EelHLfeSJfM.001.mp4,LEFT,DON'T KNOW,RIGHT,RIGHT,RIGHT,LEFT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
5862,341YLJU21JZWNJKWSIME66AH9RJI2T,xmD4FKMq2rk.004.mp4,YjXUMygVw7U.005.mp4,LEFT,DON'T KNOW,RIGHT,DON'T KNOW,DON'T KNOW,LEFT

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
6485,3T5ZXGO9DFOZASBRUX012JBALAZQZC,U-XrzfFzMkg.001.mp4,AWyKLALCUyM.000.mp4,DON'T KNOW,LEFT,LEFT,LEFT,DON'T KNOW,DON'T KNOW

,hit_id,videoLeft,videoRight,friendly,authentic,organized,comfortable,imaginative,interview
1397,31D0ZWOD0BZALRYK17QN6KTJZU70AI,RWhyKkFI3zw.000.mp4,KVepk_9iPEU.001.mp4,LEFT,LEFT,DON'T KNOW,DON'T KNOW,DON'T KNOW,RIGHT

In [ ]:
DF100

In [14]:
#videopair_0_file = pd.read_csv('/Users/lynn/Desktop/AMT Research assistantship/AMT_results/videopair_0.processed.csv')
# videopair_0_file.sample()[['authentic','organized','comfortable','imaginative','interview']]
# r1 = videopair_0_file.sample(2)[['authentic','organized','comfortable','imaginative','interview']]
# # r2 = videopair_0_file.sample()[['authentic','organized','comfortable','imaginative','interview']]

# (r1 != r2.iloc[0])

# (r1 != r2.iloc[0]).sum(axis=1)

# (r1 != r2.iloc[0]).all(axis=1)